---
- name: Install and Configure Nginx Web Server
  hosts: web
  become: true
  gather_facts: true
  
  vars: 
    nginx__replace_nginx_conf: true
    nginx__listen_port: 8080
    nginx__source_folder: .
    nginx__destin_folder: /etc/nginx/

  tasks:
    
  - block:  # **** REDHAT **** #

      - name: Install Repo epel-release
        yum: name=epel-release state=present
        tags: repo-install

      - name: Install Nginx Web Server
        yum: name=nginx state=latest
        notify:
          - Start Nginx Web Service for RedHat
        tags: install

      - name: Replace Config nginx.conf with Template where Default Port 8080
        template: src={{ nginx__source_folder }}/nginx.conf.j2  dest={{ nginx__destin_folder}}/nginx.conf  mode=0544
        notify: 
          - Restart Nginx Web Server for RedHat 
        when: nginx__replace_nginx_conf == true
        tags: configuration 
    
    when: ansible_os_family == "RedHat"

  handlers:
  - name: Start Nginx Web Service for RedHat
    systemd: name=nginx state=started enabled=yes
    when: ansible_os_family == "RedHat"

  - name: Restart Nginx Web Server for RedHat
    systemd: name=nginx state=restarted
    when: ansible_os_family == "RedHat"      

